### ISSUE TITLE
Depraciation warnings and Breaking change in changelogs

### ISSUE THREAD

**Issue by sachaarbonel** [rushio-consulting/rc_router#6]
Hi guys, it would be nice to add some depreciation warnings and breaking changes in changelogs.

RcRouteParams => `RcRouteParameters`
pathParams => `pathParameters`
handle(c) => `handle(context: c,routeSettings: routeSettings)`

**Comment by kevin-sakemaer** [comment]
Thanks for the reminder :)
We will do it better in the next version.

Also if the version bump here we come from 0.0.x to 0.1.x so expect to have breaking.
